# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-AE7BnL9B1t1c3OBWGuNpGbqBrvjnOO
"""


import pickle
import streamlit as st


from streamlit_option_menu import option_menu

genderclassification_model = pickle.load(open('best_model.sav','rb'))

with st.sidebar:

    selected = option_menu('PEHCHAN',
                           [
                           'Gender Prediction',
                           ],
                          icons=['female','male'],
                          default_index=0)

if (selected == 'PEHCHAN'):

    st.title('Gender Prediction using ML')

    col1, col2 = st.columns(2)

    with col1:
        Height = st.text_input('Height')

    with col2:
        Weight = st.text_input('Weight')

gender_prediction = ''

if st.button('AO JANE'):
      Height = float(Height)
      Weight = float(Weight)

gen_diagnosis = genderclassification_model.predict([[Height, Weight]])

if (gen_diagnosis[0] == male):
          gen_diagnosis = 'The person is male'
        else:
          gen_diagnosis = 'The person is female'

    st.success(gen_diagnosis)
